baseURL = "https://rodrigocmoraes.github.io/"
languageCode = "en-us"
title = "Rodrigo's Blog"
theme = "yinyang"
publishDir = "docs"
DefaultContentLanguage = "en"

[author]
  name = "Moraes"
  homepage = "https://rodrigocmoraes.github.io/"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
  [languages.pt]
    contentDir = "content/pt"
    languageName = "Portuguese"
    weight = 2

[params]
mainSections = ["posts"]
headTitle = "Rodrigo C. Moraes"
disqus = "rodrigocmoraes"
extraHead = ''

[[params.socials]]
name = "About Me"
link = "https://www.linkedin.com/in/rodrigocmoraes-05843256/?locale=en_US" # TODO: add link to about me

[[params.socials]]
name = "Github"
link = "https://github.com/RodrigoCMoraes"

[[params.socials]]
name = "LinkedIn"
link = "https://www.linkedin.com/in/rodrigocmoraes-05843256/?locale=en_US"

[[params.socials]]
name = "RSS Feed"
link = "/index.xml"
